server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 30
      max: 1000
      connection-timeout: 5000
  servlet:
    context-path: /pel-project

spring:
  datasource:
    url: jdbc:mysql://123.207.214.90:3306/luxixi?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: lxy960506
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 123.207.214.90
    port: 6379
    password: lxy561021...
    timeout: 3000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    #设置时区
    time-zone: GMT+8


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.luxixi.domain.entity

#打印sql
#logging:
#  level:
#    com.luxixi.dao: DEBUG

wx:
  mp:
    useRedis: true
    redisConfig:
      host: 123.207.214.90
      port: 6379
      password: lxy561021...
      database: 0
      timeout: 3000
    configs:
      - appId: wx478a1b8779dd57fd # 第一个公众号的appid
        secret: 11712d404d9c688b57d00333741cd89f # 公众号的appsecret
        token:  # 接口配置里的Token值
        aesKey:  # 接口配置里的EncodingAESKey值
